[manifest]
version = "1.0.0"
priority = 0

# Add create_shop_booster context
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if _type == 'Base' then"
position = "before"
payload = '''
if _type == 'Planet' and next(find_joker('j_stanczyk_2')) then
    forced_key = 'c_black_hole'
end
'''
match_indent = false